# Generated by Django 2.0 on 2018-06-08 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default='', max_length=255, unique=True)),
                ('email', models.EmailField(default='mymailisrequired', max_length=255, verbose_name='email address')),
                ('ref_id', models.CharField(max_length=120, null=True, unique=True)),
                ('ip_address', models.CharField(default='ABC', max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=120, null=True)),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('is_member', models.BooleanField(default=False, verbose_name='Is Paid Member')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('friend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(default=False, max_length=200)),
                ('center', models.CharField(default=False, max_length=200)),
                ('location', models.CharField(default=False, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content1', models.TextField(blank=True)),
                ('content2', models.TextField(blank=True)),
                ('content3', models.TextField(blank=True)),
                ('content4', models.TextField(blank=True)),
                ('content5', models.TextField(blank=True)),
                ('content6', models.TextField(blank=True)),
                ('content7', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_up', models.TextField(default='')),
                ('outline', models.FileField(blank=True, upload_to='https://storage.googleapis.com/bezop-uploads/media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(blank=True, upload_to='https://storage.googleapis.com/bezop-uploads/media/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ldtkc_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='https://storage.googleapis.com/bezop-uploads/media/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ldtkc_gallery', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay33', models.BooleanField(default=False)),
                ('pay67', models.BooleanField(default=False)),
                ('pay200', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(default='', max_length=100)),
                ('home_address', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255, unique=True, verbose_name='email address')),
                ('ip_address', models.CharField(default='ABC', max_length=120)),
                ('sex', models.CharField(blank=True, max_length=11, null=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('company', models.CharField(blank=True, max_length=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occupation', models.CharField(blank=True, max_length=120, null=True)),
                ('pick_your_course', models.CharField(choices=[('Pick a Course', 'Pick a Course'), ('MS Excel [Basic & Intermediate]', 'MS Excel [Basic & Intermediate]'), ('MS Excel [Advanced Masterclass]', 'MS Excel [Advanced Masterclass]'), ('MS PowerPoint [Advanced Masterclass]', 'MS PowerPoint [Advanced Masterclass]'), (' Essential MS Excel for HR Professionals ', ' Essential MS Excel for HR Professionals '), (' Excel Dashboard for Business Intelligence ', ' Excel Dashboard for Business Intelligence '), ('Financial Modelling', 'Financial Modelling'), ('Web Design for Beginners', 'Web Design for Beginners'), (' Programming(Python)', ' Programming(Python)'), ('Web Design for Advance Learners', 'Web Design for Advance Learners')], default='Pick a Course', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=False, max_length=200)),
                ('content', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ldtkc_resource', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default=False, max_length=100)),
                ('testimonial', models.TextField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ldtkc_testimonial', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
