# Generated by Django 2.0 on 2018-06-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldtkc', '0002_satisfiedclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='heading',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
