# Generated by Django 2.0 on 2018-10-09 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldtkc', '0003_courses_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=False, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addcourse_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.FileField(blank=True, max_length=1000, upload_to='https://storage.googleapis.com/bezop-uploads/media/'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='outline',
            field=models.FileField(blank=True, max_length=10000, null=True, upload_to='https://storage.googleapis.com/bezop-uploads/media/'),
        ),
        migrations.AlterField(
            model_name='satisfiedclient',
            name='image',
            field=models.ImageField(blank=True, upload_to='https://storage.googleapis.com/bezop-uploads/media/'),
        ),
    ]
