# Generated by Django 2.0 on 2019-03-13 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldtkc', '0006_auto_20190307_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='ref_id',
        ),
    ]
