# Generated by Django 2.0 on 2019-03-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldtkc', '0008_auto_20190313_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='full_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
