# Generated by Django 2.0 on 2019-03-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldtkc', '0009_myuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='pick_your_course',
            field=models.CharField(default='Pick a Course', max_length=100),
        ),
    ]
