# Generated by Django 2.0 on 2019-03-20 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ldtkc', '0011_onlineclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='start_course',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
