# Generated by Django 2.0 on 2019-03-20 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldtkc', '0013_auto_20190320_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='start_course',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 17, 26, 3, 501085)),
        ),
    ]
