# Generated by Django 2.0 on 2019-04-05 12:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldtkc', '0014_auto_20190320_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('video', models.FileField(blank=True, max_length=1000, upload_to='https://storage.googleapis.com/bezop-uploads/media/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='onlineclass',
            name='description',
        ),
        migrations.RemoveField(
            model_name='onlineclass',
            name='video',
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='slug',
            field=models.SlugField(default='', max_length=1500, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='start_course',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 31, 12, 14, 26, 722169)),
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='online_video',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='online_video', to='ldtkc.OnlineVideo'),
        ),
    ]
