# Generated by Django 2.0 on 2019-04-25 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldtkc', '0016_auto_20190405_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='start_course',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 20, 15, 1, 20, 914599)),
        ),
        migrations.AlterField(
            model_name='onlinevideo',
            name='video',
            field=models.FileField(blank=True, max_length=1000, upload_to='https://storage.googleapis.com/bezop-uploads/media'),
        ),
    ]
