# Generated by Django 2.0 on 2019-06-26 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldtkc', '0021_auto_20190623_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='start_course',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 21, 8, 21, 8, 258657)),
        ),
    ]
