# Generated by Django 2.0 on 2019-06-26 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldtkc', '0022_auto_20190626_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatistic',
            name='company',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='start_course',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 21, 8, 38, 32, 996005)),
        ),
    ]
