# Generated by Django 2.0 on 2019-06-26 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldtkc', '0023_auto_20190626_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='start_course',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 21, 8, 48, 53, 410207)),
        ),
    ]
