# Generated by Django 2.0 on 2019-06-28 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldtkc', '0026_auto_20190626_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatistic',
            name='department',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='start_course',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 23, 11, 36, 28, 714690)),
        ),
    ]
