# Generated by Django 3.0 on 2021-12-26 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldtkc', '0028_auto_20211223_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='start_course',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 10, 39, 57, 880555)),
        ),
    ]
